Add --list argument

diff --git a/wshandler b/wshandler
--- a/wshandler
+++ b/wshandler
@@ -11,21 +11,29 @@ help()
     EXIT_CODE=${1:-"0"}
     echo "Usage (default values are shown in curly braces):"
     echo "  wshandler [<COMMON_ARGS>] [<COMMAND_ARGS>] <COMMAND> <COMMAND_ARGS>"
+    echo ""
+    echo "Notation:"
+    echo "  <REQUIRED ARGUMENT>"
+    echo "  {DEFAULT VALUE}"
+    echo "  [OPTIONAL ARGUMENT]"
+    echo "  (VALID OPTIONS IN A LIST)"
+    echo ""
     echo "Common arguments:"
-    echo "  -y|--yq <YQ_BINARY>         {yq}"
-    echo "  -r|--root <WORKSPACE_ROOT>  {./}"
-    echo "  -c|--cache <CACHE_DIR>      {<WORKSPACE_ROOT>}"
-    echo "  -t|--type rosinstall|repos  {repos}"
-    echo "  -i|--indent 1|2|3...        {4}"
-    echo "  -k|--keep-going             {false}"
-
+    echo "  -y|--yq <YQ_BINARY>         {yq}                    # override yq path"
+    echo "  -r|--root <WORKSPACE_ROOT>  {./}                    # parent of --list if it is a path"
+    echo "  -c|--cache <CACHE_DIR>      {<WORKSPACE_ROOT>}      # temporary files created here"
+    echo "  -t|--type rosinstall|repos  {repos}                 # repository list format"
+    echo "  -i|--indent 1|2|3...        {4}                     # default indentation in yaml repository list"
+    echo "  -k|--keep-going             {false}                 # do not stop on errors"
+    echo "  -l|--list <FILENAME>        {.rosinstall|.repos}    # default depends on --type"
+    echo ""
     echo "List commands:"
     echo "  Information:"
     echo "    status"
     echo "    is_source_space"
     echo "  Initialization:"
-    echo "    [-p|--policy policy1[,policy2] ({default}|shallow|nolfs)] clone git <LIST_REPOSITORY> [<BRANCH>]"
-    echo "    [-p|--policy policy1[,policy2] ({default}|shallow|nolfs)] init [git <PACKAGE_REPOSITORY> ...]"
+    echo "    [-p|--policy <POLICY1[,POLICY2]> ({default}|shallow|nolfs)] clone git <LIST_REPOSITORY> [<BRANCH>]"
+    echo "    [-p|--policy <POLICY1[,POLICY2]> ({default}|shallow|nolfs)] init [git <PACKAGE_REPOSITORY> ...]"
     echo "  Modification:"
     echo "    [-p|--policy {ask}|add|show] scrape"
     echo "    add git <PACKAGE_NAME> <PACKAGE_URL> <PACKAGE_VERSION>"
@@ -34,10 +42,10 @@ help()
     echo "    remove <PACKAGE_NAME>"
     echo "    remove_by_url <PACKAGE_URL>"
     echo "    [-p|--policy {keep}|replace] merge <LIST_FILENAME>"
-
+    echo ""
     echo "Package repository commands:"
     echo "  Global:"
-    echo "    [-j|--jobs <NUM_THREADS> {1}] [-p|--policy policy1[,policy2] ({default}|shallow|nolfs|rebase)] update"
+    echo "    [-j|--jobs <NUM_THREADS> {1}] [-p|--policy <POLICY1[,POLICY2]> ({default}|shallow|nolfs|rebase)] update"
     echo "    [-j|--jobs <NUM_THREADS> {1}] clean"
     echo "    [-j|--jobs <NUM_THREADS> {1}] [-s|-source {git}] foreach '<COMMAND>'"
     echo "    prune"
@@ -50,7 +58,7 @@ help()
     echo "    commit '<MESSAGE>'"
     echo "  Local:"
     echo "    unshallow <PACKAGE_NAME>"
-
+    echo ""
     echo "wshandler installation commands:"
     echo "  install_test_deps"
     echo "  [-p|--policy {skip_yq}|snap|download] install <BIN_PATH {~/bin}>"
@@ -398,12 +406,26 @@ check_workspace()
     fi
     WSH_YQ=("${WSH_YQ_BINARY}" --indent "${WSH_INDENT}")
 
-    WSH_WORKSPACE_ROOT=${WSH_WORKSPACE_ROOT:-"./"}
-    test -d "${WSH_WORKSPACE_ROOT}" || (echo "'${WSH_WORKSPACE_ROOT}' does not exist" && false)
-    WSH_WORKSPACE_ROOT="$(realpath "${WSH_WORKSPACE_ROOT}")/"
 
     WSH_WORKSPACE_TYPE=${WSH_WORKSPACE_TYPE:-"repos"}
-    WSH_REPOLIST="${WSH_WORKSPACE_ROOT}/.${WSH_WORKSPACE_TYPE}"
+    if [ -n "${WSH_REPOLIST}" ] && [ -f "${WSH_REPOLIST}" ]
+    then
+        WSH_WORKSPACE_ROOT=$(realpath "$(dirname "${WSH_REPOLIST}")")
+        WSH_REPOLIST=$(realpath "${WSH_REPOLIST}")
+    else
+        WSH_WORKSPACE_ROOT=${WSH_WORKSPACE_ROOT:-"./"}
+        WSH_WORKSPACE_ROOT="$(realpath "${WSH_WORKSPACE_ROOT}")/"
+
+        if [ -n "${WSH_REPOLIST}" ]
+        then
+            WSH_REPOLIST="${WSH_WORKSPACE_ROOT}/${WSH_REPOLIST}"
+        else
+            WSH_REPOLIST="${WSH_WORKSPACE_ROOT}/.${WSH_WORKSPACE_TYPE}"
+        fi
+    fi
+
+    test -d "${WSH_WORKSPACE_ROOT}" || (echo "'${WSH_WORKSPACE_ROOT}' does not exist" && false)
+
     WSH_CACHE_DIR=${WSH_CACHE_DIR:-"${WSH_WORKSPACE_ROOT}/.wshandler"}
 
     if [ ! -f "${WSH_REPOLIST}" ]
@@ -697,6 +719,7 @@ WSH_XARGS=(xargs --no-run-if-empty -L 1 -P "${WSH_JOBS}")
 WSH_KEEP_GOING=""
 WSH_YQ_BINARY="yq"
 WSH_SOURCE_TYPE="git"
+WSH_REPOLIST=
 
 while [[ $# -gt 0 ]]
 do
@@ -735,6 +758,10 @@ do
 
         -s|--source)
             WSH_SOURCE_TYPE=$2
+            shift; shift;;
+
+        -l|--list)
+            WSH_REPOLIST=$2
             shift; shift;;
 
         clone|init)
